#!/bin/bash

# Gateway admin script
#
# Tools to do routine stuff with the Kannel Gateway.
# |-_-|

. box_admin

if [[ $gateway_name =~ ^\ *$ ]]
then
    echo \$gateway_name is not set. Don\'t panic\; we shall \
         help you to set it. Please provide the name of your \
         gateway at the next prompt. >&2
    __infect_bashrc
fi

# Wrapper Scripts
# startbbox, startsmsbox, startsqlbox

startbbox()
{
    local store_type= dlr_store=
    store_type=$(get_store_type)
    [ $store_type = "spool" ] && {
        check_spool store
        [ $? -eq 0 ] || return        
    }
    dlr_store=$(get_dlr_storage)
    case $dlr_store in
        mysql)
            check_mysql dlrstore
            [ $? -eq 0 ] || return
            ;;
        spool)
            check_spool dlr
            [ $? -eq 0 ] || return
            ;;
        redis)
            :
            ;;
        cassandra)
            :
            ;;
        internal)
            disable_external_dlr_storage
            ;;
        *)
    esac
    check_included_paths $GW_CONF
    [ $? -eq 0 ] || return
    check_user
    check_log_path
    box_start bearerbox
}

startsmsbox()
{
    check_smsbox_port
    [ $? -eq 0 ] || {
        echo Bearerbox\'s smsbox-port is not open, \
             Bearerbox might not be running.
        return 2
    }
    check_user
    check_log_path
    box_start smsbox
}

startsqlbox()
{
    local key= conf=
    [ $# -gt 0 ] && key=$1
    [ -z $key ] && conf=$(get_sqlbox_conf) || \
            conf=$(get_sqlbox_conf $key)
    [ -z $conf ] && {
        echo Config file not found. \
             Usage: startsqlbox [key]
        return 2
    }
    check_smsbox_port
    [ $? -eq 0 ] || {
        echo Bearerbox\'s smsbox-port is not open, \
             Bearerbox might not be running.
        return 2
    }
    check_user
    check_log_path
    box_start sqlbox $conf
}
