#!/bin/bash

# Variables

# ---- Gateway Name
# ---- This is presumably set from the presiding
# ---- user's .bashrc or .bash_profile.
GW_NAME=$gateway_name

# ---- Current Working Directory
[[ $(dirname $BASH_SOURCE) = '.' ]] &&
    GW_ADMIN_CWD=$(pwd) || \
    GW_ADMIN_CWD=$(pwd)/$(sed 's:^\./::' <<< $(dirname $BASH_SOURCE))

# ---- Needed in check_pkgs
declare -A os_pkgs=(
    [debian]='build-essential|netcat-openbsd|libxml2-dev|libmariadbclient-dev-compat|libpcre3-dev|wget'
    [ubuntu]='build-essential|netcat-openbsd|libxml2-dev|libmariadb2|libpcre3-dev|wget'
    [centos]='nmap-ncat|libxml2-devel|mariadb-devel|pcre2-devel|wget'
)
# ---- Needed in check_pkgs
declare -a missing_pkgs

# ---- Needed in gw_install_pkg
declare -A os_installer=(
    [Debian]='apt-get install -y'
    [Centos]='yum install -y'
    [Ubuntu]='apt install -y'
)

# ---- Needed in gw_pkg_check
declare -A os_chk=(
    [Debian]='dpkg --status'
    [Centos]='rpm -q'
    [Ubuntu]='dpkg --status'
)

# ---- Needed in box_os_detect
declare -A detect_stings=(
    [debian]=debian
    [centos]=centos
    [ubuntu]=ubuntu
)

# ---- Some Regexes
declare -A box_regexes=(
    [aux_box]='\<(sql|(open)?smpp)box\>'
    [main_box]='\<(bearer|sms)box\>'
    [smsbox]='\<smsbox\>'
    [bbox]='\<bearerbox\>'
)

# ---- Used when checking mysql dlr storage and sqlbox connectivity to DB
declare -A db_credentials=(
    [host]=""
    [port]=""
    [username]=""
    [password]=""
)

# ---- Workspace Directory
INST=/tmp/kannel

# ---- Gateway Directory
GW_DIR=/opt/gw/kannel

# ---- Home of the boxes
BINDIR=$GW_DIR/sbin

# ---- Daemonizer numero uno
RUN_BOX=run_kannel_box

# ---- Daemonizer numero dos
START_STOP_DAEMON=start-stop-daemon

# ---- Them boxes
BBOX=bearerbox SMSBOX=smsbox SQLBOX=sqlbox SMPPBOX=opensmppbox

# ---- Config Tarball
CONF_TARBALL=$GW_ADMIN_CWD/gw_config.tar.gz

# ---- The Almighty Configs
GW_CONF=/etc/kannel/$GW_NAME/kannel.conf
SQLBOX_CONF= SMPPBOX_CONF=

# ---- Gateway Spool Dir
GW_SPOOL_DIR=/var/spool/kannel

# ---- PID and stuff
RUNDIR=/var/run/kannel

# ---- Snippet Directory
SNIPPETS=$GW_ADMIN_CWD/snippets

# ---- Your children shall belong to
GW_USER=kannel

# ---- Logging and stuff
LOG_PREFIX=/var/log/kannel LOGDIR=$LOG_PREFIX/$GW_NAME

# ---- Localhost
LHOST=127.0.0.1

# ---- Gateway Source URL
GW_SRC_URL='https://kannel.org/download/1.4.5/gateway-1.4.5.tar.gz'

# ---- Options to start the gateway boxes with the parachute option.
# ---- This has since been proven "superflous" as the run_kannel_box
# ---- binary does the thing that --parachute does while also as
# ---- a bonus making the restart interval configurable and handling
# ---- the creation and deletion of the pid file automatically for
# ---- you.
BOX_OPTIONS="--daemonize \
	 --parachute \
	 --user $GW_USER \
	 --pid-file $RUNDIR"

# ---- Min delay for run_kannel_box
RUN_BOX_MIN_DELAY=15

# ---- Panic Script (Ran after bearerbox's child
#      fails and is restarted by its watcher
#      parent process.)

PANIC_SCRIPT=$GW_SCRIPT_DIR/panic_routine.sh

# ---- Gateway Script Dir
TARGET_SCRIPT_DIR=/usr/local/scripts/gateway/admin
