#!/bin/bash

# Gateway admin script
#
# Tools to do routine stuff with the Kannel Gateway.
# |-_-|

gw_admin_root=$(dirname $BASH_SOURCE)
. $gw_admin_root/box_admin

if [[ $gateway_name =~ ^\ *$ ]]
then
    gateway_name={{ salt['pillar.get']('kannel:data:gwname') }} 
    # echo \$gateway_name is not set. Don\'t panic\; we shall \
    #      help you to set it. Please provide the name of your \
    #      gateway at the next prompt. >&2
fi

# Wrapper Scripts
# startbbox, startsmsbox, startsqlbox

startbbox()
{
    local store_type= dlr_store=
    store_type=$(get_store_type)
    [ $store_type = "spool" ] && {
        check_spool store
        [ $? -eq 0 ] || return        
    }
    dlr_store=$(get_dlr_storage)
    case $dlr_store in
        mysql)
            check_mysql dlrstore
            [ $? -eq 0 ] || return
            ;;
        spool)
            check_spool dlr
            [ $? -eq 0 ] || return
            ;;
        redis)
            :
            ;;
        cassandra)
            :
            ;;
        internal)
            disable_external_dlr_storage
            ;;
        *)
    esac
    check_included_paths $GW_CONF
    [ $? -eq 0 ] || return
    check_user
    check_log_path
    box_start bearerbox
}

startsmsbox()
{
    local key= conf=
    [ $# -gt 0 ] && key=$1
    [ -z $key ] && conf=$(get_smsbox_conf) || \
            conf=$(get_smsbox_conf $key)
    [ -z $conf ] && {
        echo Config file not found. \
             Usage: startsmsbox [key]
        return 2
    }
    check_smsbox_port
    [ $? -eq 0 ] || {
        echo Bearerbox\'s smsbox-port is not open, \
             Bearerbox might not be running.
        return 2
    }
    check_user
    check_log_path
    box_start smsbox $conf
}

startsqlbox()
{
    local key= conf=
    [ $# -gt 0 ] && key=$1
    [ -z $key ] && conf=$(get_sqlbox_conf) || \
            conf=$(get_sqlbox_conf $key)
    [ -z $conf ] && {
        echo Config file not found. \
             Usage: startsqlbox [key]
        return 2
    }
    check_smsbox_port
    [ $? -eq 0 ] || {
        echo Bearerbox\'s smsbox-port is not open, \
             Bearerbox might not be running.
        return 2
    }
    check_user
    check_log_path
    box_start sqlbox $conf
}

startsmppbox()
{
    local conf=
    [ $# -ge 1 ] && conf=${1} || {
        echo Please provide the config file. >&2
        return 3
    }
    check_smppbox_port $conf
    [ $? -eq 0 ] || {
        echo Bearerbox\'s smppbox-port is not open, \
             Bearerbox might not be running.
        return 2
    }
    check_user
    check_log_path
    box_start smppbox $conf
}
